### ISSUE TITLE
Build error when linking against an older glibc

### ISSUE THREAD

**Issue by otavio** [rust-embedded/meta-rust-bin#83]
The PR #82 solved the linking error I had (issue #70) but using this layer on master has raised another issue:

```
| /home/otavio/src/updatehub/yocto/build/tmp/work/core2-64-oel-linux/updatehub/1.1.90-r0/target/release/build/proc-macro2-378cfb6b48440bd3/build-script-build: /usr/lib/libc.so.6: version `GLIBC_2.32' not found (required by /home/otavio/src/updatehub/yocto/build/tmp/work/core2-64-oel-linux/updatehub/1.1.90-r0/target/release/build/proc-macro2-378cfb6b48440bd3/build-script-build)
```

So, looking at the logs that seem to happen is that OE-Core has glibc 2.32 and my Arch Linux has the 2.31. I am out of ideas on how to address this.

It is important to mention that this happens with and without #82 applied. So this is not a regression.

**Comment by otavio** [comment]
Yes. In fact it fails if the host has older version. Upgrading the host "fixed" it.

**Comment by jameshilliard** [comment]
The fix is available as of rust `1.54.0` stable, you can enable it like [this](https://github.com/buildroot/buildroot/commit/4b2be770b8a853a7dd97b5788d837f0d84923fa1).

**Comment by nastevens** [comment]
@jameshilliard Am I missing something or doesn't this still require a nightly version of cargo? I understand it works with stable rustc, but it's still a problem to include nightly versions of cargo in meta-rust-bin.

**Comment by jameshilliard** [comment]
> doesn't this still require a nightly version of cargo

Nope, works with stable cargo.

**Comment by jameshilliard** [comment]
Simpler way, just set this in your env when building:
```
__CARGO_TEST_CHANNEL_OVERRIDE_DO_NOT_USE_THIS="nightly"
CARGO_UNSTABLE_TARGET_APPLIES_TO_HOST="true"
CARGO_TARGET_APPLIES_TO_HOST="false"
```
